//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carte
    {
        public int id_carte { get; set; }
        public string titlu { get; set; }
        public int id_autor { get; set; }
        public int id_categorie { get; set; }
        public int id_serie { get; set; }
        public string descriere { get; set; }
        public Nullable<int> nr_volum { get; set; }
    
        public virtual Carte Carte1 { get; set; }
        public virtual Carte Carte2 { get; set; }
        public virtual Carte Carte11 { get; set; }
        public virtual Carte Carte3 { get; set; }
        public virtual Carte Carte12 { get; set; }
        public virtual Carte Carte4 { get; set; }
    }
}
