//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstoricCitire
    {
        public int id_istoric { get; set; }
        public int id_utilizator { get; set; }
        public int id_carte { get; set; }
        public System.DateTime data_accesare { get; set; }
        public string actiune { get; set; }
    
        public virtual IstoricCitire IstoricCitire1 { get; set; }
        public virtual IstoricCitire IstoricCitire2 { get; set; }
        public virtual IstoricCitire IstoricCitire11 { get; set; }
        public virtual IstoricCitire IstoricCitire3 { get; set; }
    }
}
