//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eBooksEntities : DbContext
    {
        public eBooksEntities()
            : base("name=eBooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public void SaveChanges()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<Autor> Autors { get; set; }
        public virtual DbSet<Carte> Cartes { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<IstoricCitire> IstoricCitires { get; set; }
        public virtual DbSet<Serie> Series { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipAbonament> TipAbonaments { get; set; }
        public virtual DbSet<Utilizator> Utilizators { get; set; }
    }
}
