//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipAbonament
    {
        public int id_tip_abonament { get; set; }
        public string denumire { get; set; }
        public Nullable<int> limita_carti_pe_luna { get; set; }
        public bool acces_serii_complete { get; set; }
        public bool permite_descarcare { get; set; }
    }
}
