//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizator
    {
        public int id_utilizator { get; set; }
        public string nume_utilizator { get; set; }
        public string email { get; set; }
        public string parola { get; set; }
        public System.DateTime data_inregistrare { get; set; }
        public int id_tip_abonament { get; set; }
        public int carti_citite_luna { get; set; }
    
        public virtual Utilizator Utilizator1 { get; set; }
        public virtual Utilizator Utilizator2 { get; set; }
    }
}
