// <auto-generated />
namespace Repository_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migrare1_25_10_2025 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrare1_25_10_2025));
        
        string IMigrationMetadata.Id
        {
            get { return "202510251621328_migrare1_25_10_2025"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
