// <auto-generated />
namespace Repository_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ModificareAutorSiAdaugareEditura_2025_10_20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificareAutorSiAdaugareEditura_2025_10_20));
        
        string IMigrationMetadata.Id
        {
            get { return "202510261634506_ModificareAutorSiAdaugareEditura_2025_10_20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
