// <auto-generated />
namespace Repository_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AdaugaTabeleNoi_2025_10_25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdaugaTabeleNoi_2025_10_25));
        
        string IMigrationMetadata.Id
        {
            get { return "202510251640160_AdaugaTabeleNoi_2025_10_25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
