// <auto-generated />
namespace Repository_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddSerieCategorieToCarte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSerieCategorieToCarte));
        
        string IMigrationMetadata.Id
        {
            get { return "202501090000000_AddSerieCategorieToCarte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "202501090000000_AddSerieCategorieToCarte"; }
        }
    }
}
